<?php

class IndexController extends Controller
{
    public $view = 'index';
    public $title;

    function __construct()
    {
        parent::__construct();
        $this->title .= ' | Главная';
    }

    public function index($data)
    {
        return ['user'=> isset($_SESSION['user_name'])?$_SESSION['user_name']:'']; // TODO: Change the autogenerated stub

    }


}